### ISSUE TITLE
latest dependency support

### ISSUE THREAD

**Issue by bdwain** [LaxarJS/webpack-jasmine-html-runner-plugin#11]
Hi,
Are there any plans to add support for jasmine 3 and webpack 4?

Thanks!

**Comment by x1B** [comment]
Hi @bdwain, sorry for taking so long to get back to you. 

Updating the dependencies is something I'd like to do, but I'm afraid I won't get to it within the next couple of weeks. Im open to accepting PR's to advance this, though.

**Comment by bdwain** [comment]
Cool I'll look into it. Thanks

**Comment by x1B** [comment]
Implemented on `master` (`v0.9.0`).

Thanks @bdwain
